name: Generate and Release OTA

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.6'

      - name: Install dependencies
        run: |
          pip install zigpy || true

      - name: Extract OTA version from main.cpp
        id: extract_version
        run: |
          VERSION=$(grep '^#define OTA_UPGRADE_RUNNING_FILE_VERSION' main/main.cpp | sed -E 's/^#define[[:space:]]+OTA_UPGRADE_RUNNING_FILE_VERSION[[:space:]]+(0x[0-9a-fA-F]+).*/\1/')
          echo "Found version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Run script to generate OTA
        run: |
          python OTAcreate/image_builder_tool.py \
            --create OTAcreate/Zigbee_OTA_Client.ota \
            --manuf-id 0x1001 \
            --image-type 0x1011 \
            --version ${{ steps.extract_version.outputs.version }} \
            --tag-id 0x0000 \
            --tag-file build/OmniSensHome.bin

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.extract_version.outputs.version }}
          name: "Release v${{ steps.extract_version.outputs.version }}"
          body: "Automated OTA file generated from latest push"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload OTA file to release
        uses: softprops/action-gh-release@v2
        with:
          files: OTAcreate/Zigbee_OTA_Client.ota
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
